<?php

namespace ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{

    public function showOrderedByName()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p FROM ContactsBundle:Person p
             ORDER BY p.name'
        );
        return $query->getResult();
    }

    public function searchBy($val)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p FROM ContactsBundle:Person p
             WHERE p.name LIKE :val OR p.surname
             LIKE :val
             ORDER BY p.name'
        );
        $query->setParameter('val', '%' . $val . '%');
        return $query->getResult();
    }
}
